spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8072/
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
              # globaltimeoutconfiguration :: circuitbreaker has its own timeout, but those services whihc does not have the circuit breaker can use this global timeout
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:5050/realms/master/protocol/openid-connect/certs

info:
  app:
    name: "GatewayServer"
    description: "Gate h ji"
    version: "1.0.1"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50

logging:
  level:
    com:
      example:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"