spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://localhost:8072
 
server:
  port: "5090"  
  
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
  endpoint:
    health:
      probes:
        enabled: true

  health:
    liveness-ready:
      enabled: true
    readiness-ready:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      example:
        eurekaserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"