spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config
        git:
          uri: GITHUB_URI
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: USERNAME
    password: PASSWORD
    
server:
  port: 8072
  
encrypt:
  key: ENCRYPTED_KEY
 
management:
  endpoints:
    web:
      exposure:
        include: "*"   
        
  health:
    readiness-ready:
      enabled: true
    liveness-ready:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      example:
        configserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
