spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: emailsms-communication
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092

server:
  port: 9091