spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: DawnHorizon0@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8080/
     
  profiles:
    active: prod 
  
  rabbitmq:
    host: local
    port: 5672
    username: guest
    password: guest
       
server:
  port: 8080  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"