FROM eclipse-temurin:21.0.11_10-jre-ubi9-minimal

LABEL maintainer = harshitsumra

COPY target/accounts-service-0.0.1-SNAPSHOT.jar accounts-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "accounts-service-0.0.1-SNAPSHOT.jar"]
