spring:
  application:
    name: cards-services
  datasource:
    url: jdbc:mysql://localhost:3306/cards_service
    username: root
    password: DawnHorizon0@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8072/

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
         
  profiles:
    active: default
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
server:
  port: 9000
  
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:5090/eureka/
      
info:
  app:
    name: "cards"
    description: "cards application"
    version: "1.0.0"
    
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50

logging:
  level:
    com:
      microservices:
        cards_services: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"